on:
  pull_request:
    branches:
    - master
    
jobs:
  build_mac:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: g++ build
      run: g++ -o mechanismsynthesis -I ./eigen-3.4.0 ./*.cpp
